### ISSUE TITLE
Rework "nm_settings.json"

### ISSUE THREAD

**Issue by richardkoehler** [neuromodulation/py_neuromodulation#114]
There are some minor issues in the nm_settings.json that we could improve:

1. Add settings for STFT. Right now STFT requires the sampling frequency to be 1000 Hz
2. Re-think frequency bands: Either we define them separate from FFT, STFT or bandpass, and then they can't be specifically adapted to each method. Or you can define them inside of each method (FFT, STFT, bandpass separately). But right now, FFT and STFT are "taking" the info from the bandpass settings. Also, right now the fband_names are hard-coded in nm_features.py (not sure why this is the case?)
3. Make notch filter settings more flexible (i.e. let the user define how many harmonics he would like to remove).

**Comment by timonmerk** [comment]
@richardkoehler Thanks for notifying!
I am sorry that I had been slow merging my local changed in main. But will still do it today. 

I think point 1 and 2 are implemented in my recent branch: https://github.com/neuromodulation/py_neuromodulation/blob/Figures_0610/pyneuromodulation/nm_settings.json

Point 3 is a good one. I think adding the maximum possible number of harmonics instead of a fixed number will be the way to go. Otherwise I couldn't think of a use case where you want to keep a line noise harmonic

**Comment by richardkoehler** [comment]
Oh no I had just implemented the current main branch and done a ton of fixes haha
I will try to merge them and them maybe make a pull from a separate branch.
Concerning point 3 maybe we could a nm_settings item called ["notch_filter_settings"], where you can specify "freq": 50 and "harmonics": int | "max", where "max" then gets rid of all possible harmonics (up until Nyquist frequency). Additionally we could then avoid having to read the line noise from the raw file.

**Comment by timonmerk** [comment]
@richardkoehler Again, sorry for that. 
Before you try to merge, let's have a meeting about that. 
I also updated the files quite extensively, so we could discuss which makes most sense.

Regarding the line_noise, we actually know this from BIDS.
Since we didn't apply the toolbox in a real hardware setting, I would postpone it for now
