### ISSUE TITLE
Design notch filter at beginning of analysis

### ISSUE THREAD

**Issue by richardkoehler** [neuromodulation/py_neuromodulation#25]
By designing a notch filter only once at the beginning of the analysis we could probably reduce computation time

**Comment by timonmerk** [comment]
Good idea! The MNE [filter.create_filter](https://mne.tools/dev/generated/mne.filter.create_filter.html) specifies also: 

> Multiple stop bands can be specified using arrays.

So should be rather simple. The performance benefit might be not too high, since this is only done once for every analysis afterwards, but given a lot of channels it might pay off

**Comment by timonmerk** [comment]
Does not seem to be a performance issue
