### ISSUE TITLE
Test settings currently gives an error

### ISSUE THREAD

**Issue by timonmerk** [neuromodulation/py_neuromodulation#30]
@richardkoehler 
bandpass_filter_settings in settings.json currently misses the "feature_labels" keyword

![grafik](https://user-images.githubusercontent.com/38216460/113423233-5eebf480-93ce-11eb-9305-2623a1ec341d.png)

That's why test.py doesn't run through.

Also I am bit confused why settings.py is in the pyneuromodulation folder. Since this file mainly deals with testing, I would put it into tests folder

**Comment by richardkoehler** [comment]
@timonmerk True, I forgot to update the settings test.. We will probably have to update it very often with all the API changes at the moment. I will take care of it.
I put this module in the pyneuromodulation because I didn't intend test_settings simply as a test for commits, but as a function that the user can call after he specified his settings to check if they are valid. So the workflow could be specify settings -> call "test_settings()" ->  specify M1.tsv -> call "test_M1() -> start analysis.
Also, I was thinking about writing a function (similar to get_M1(), e.g. "get_settings()" ) that writes out a valid "settings.json" file for you. I would also place this function in the "settings.py" module, and then in the future all other functions that concern the settings would also go in this module. Would you agree with this?

**Comment by timonmerk** [comment]
Yes, that makes sense. I guess the settings will be quite an error source for a lot of processing, for checking before could save us some debugging time

**Comment by timonmerk** [comment]
Fixed by #33
