### ISSUE TITLE
Fix type hints project-wide

### ISSUE THREAD

**Issue by toni-neurosc** [neuromodulation/py_neuromodulation#303]
Since Pydantic will be used to validate analysis settings, and the contents of settings will be propagated to the different submodules of PyNeuro, type hints should be consistently provided, and correct, all accross the project. MyPy and PyRight are throwing a lot of static analysis errors at the time, which is unclear if they would affect Pydantic integration or not, but I think it's better to fix them, also in case users of the module are using static analysis tools themselves.

[mypy_report.txt](https://github.com/neuromodulation/py_neuromodulation/files/14995650/mypy_report.txt)
[pyright_report.txt](https://github.com/neuromodulation/py_neuromodulation/files/14995651/pyright_report.txt)

**Comment by timonmerk** [comment]
Thanks for running those tests @toni-neurosc.
It would be great to take this as an opportunity to refactor some parts of the current codebase. I had a look at the  files, and found that we can for now ignore:
 - nm_RMAP.py
 - nm_decode.py

For both I need to check what is currently necessary, and how dependencies can be reduced. 

Furthermore, I would even leave out certain modules and delete them in the dev branch for refactoring that would clean up the existing codebase:
  - nm_cohortwrapper.py
  - nm_across_patient_decoding.py
  - nm_eval_timing.py
  - nm_nolds.py (since the computation is way too slow, and not real-time compatible - at least in Python)
  - FieldTrip.py

Apart of that the main point would be to improve the validation with pydantic as an object instead of an dictionary.

**Comment by toni-neurosc** [comment]
Closed with the merge of #305
